# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
#permissions:
#  contents: write
#  packages: write
#  pull-requests: write
#  issues: write
#  repository-projects: write
jobs:
  build:
    runs-on: ubuntu-latest
#    permissions:
#      contents: write
#      packages: write

    steps:
    - uses: actions/checkout@v3
      with:
#        persist-credentials: false
        fetch-depth: 1
    - name: Set up JDK 15
      uses: actions/setup-java@v3
      with:
        java-version: '15'
        distribution: 'zulu'

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package
    - name: Test with Maven
      run: mvn clean verify --file pom.xml
    - name: Generate JaCoCo badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2
      with:
        badges-directory: badges
        generate-branches-badge: true
        generate-summary: true
    - name: Log coverage percentages to workflow output
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        echo "branches = ${{ steps.jacoco.outputs.branches }}"

    - name: Upload JaCoCo coverage report as a workflow artifact
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-report
        path: target/site/jacoco/
    - name: Commit the badge (if it changed)
      env:
        GIT_USER_NAME: github-actions
        GIT_USER_EMAIL: github-actions@users.noreply.github.com
      run: |
        if [[ `git status --porcelain` ]]; then
          git add -A
          git commit -m "Autogenerated JaCoCo coverage badges2"
          git push
        fi
    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: target/site/jacoco/
#    - name: Commit and push the coverage badges and summary file
#      if: ${{ github.event_name != 'pull_request' }}
#      run: |
#        cd badges
#        if [[ `git status --porcelain *.svg *.json` ]]; then
#          git config --global user.name 'github-actions'
#          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
#          git add *.svg *.json
#          git commit -m "Autogenerated JaCoCo coverage badges" *.svg *.json
#          git push
#        fi
    - name: Generate jar
      run: mkdir staging && cp target/*.jar staging
    - name: Copy jar
      uses: actions/upload-artifact@v3
      with:
         name: Package
         path: staging
#    - name: Lint Code Base
#      uses: docker://avtodev/markdown-lint:v1
#      with:
#        args: "**/*.md"
