# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 15
      uses: actions/setup-java@v3
      with:
        java-version: '15'
        distribution: 'zulu'

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package
    - name: Generate jar
      run: mkdir staging && cp target/*.jar staging
    - name: Copy jar
      uses: actions/upload-artifact@v3
      with:
         name: Package
         path: staging
#    - name: Lint Code Base
#      uses: docker://avtodev/markdown-lint:v1
#      with:
#        args: "**/*.md"